name: Lint

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.12'

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install black flake8 isort Flake8-pyproject

            - name: Run black
              run: |
                black . --config pyproject.toml

            - name: Run flake8
              run: |
                  flake8 . --toml-config pyproject.toml

            - name: Run isort
              run: |
                  isort . --settings-path=pyproject.toml